version: '3'
services:
  yowla:
    image: "yowladmin/yowla:latest"
    ports:
      - "80:5000"
#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: yowla
#        awslogs-region: us-east-1
#        awslogs-stream-prefix: yowla
    env_file: .env
    restart: always
    links:
      - mysql:dbserver
  mysql:
    image: "mysql/mysql-server:5.7"
    env_file: .env-mysql
    restart: always
    command: --sql_mode=""
