version: '3'
services:
  mysql:
    image: "mysql/mysql-server:5.7"
#    volumes:
#      - mysql_data:/var/lib/mysql
    env_file: .env-mysql
    restart: always
    command: --sql_mode=""
  yowla:
    #    image: "yowladmin/yowla:latest"
    build: .
#    depends_on:
#      - mysql
#    volumes_from:
#      - mysql
#    volumes:
#      - type: bind
#        source: ./app
#        target: /home/yowla/app
    #        volume:
    #          nocopy: true
    #      - ./app:/home/yowla/app

    ports:
      - "80:5000"
    #    logging:
    #      driver: awslogs
    #      options:
    #        awslogs-group: yowla
    #        awslogs-region: us-east-1
    #        awslogs-stream-prefix: yowla
    env_file: .env
    restart: always
#    command: ["./wait-for-it/wait-for-it.sh", "localhost:80", "--", "npm", "run", "migrate"]
    links:
      - mysql
#volumes:
#  mysql_data:
