"""initial

Revision ID: d1c989074a52
Revises: 51f5ccfba190
Create Date: 2021-05-14 08:58:33.568139

"""

# revision identifiers, used by Alembic.
revision = 'd1c989074a52'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
